const STATUS_CODES = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER_ERROR: 500,
};

const TOKEN_OPTIONS = {
  EXPIREY: "7d",
  ALGORITHM: "HS256",
  AUDIENCE: "http://localhost",
  ISSUER: "http://localhost",
};

export { STATUS_CODES, TOKEN_OPTIONS };
